import { useI18n, type Lang } from '../state/i18n';

const en = {
  title: 'Swasth Saathi',
  subtitle: 'Your health assistant',
  open: 'Open health assistant',
  emptyTitle: 'How can I help you today?',
  emptyBody: 'Ask about symptoms, medicines, appointments or health schemes — by typing or by voice.',
  disclaimer: 'Not a doctor. For emergencies call 108.',
  placeholder: 'Ask anything…',
  placeholderVoice: 'Type to the voice call…',
  send: 'Send message',
  stop: 'Stop generating',
  startVoice: 'Start voice mode',
  endVoice: 'End voice call',
  mute: 'Mute microphone',
  unmute: 'Unmute microphone',
  toChat: 'Switch to chat',
  toVoice: 'Back to voice view',
  connecting: 'Connecting…',
  listening: 'Listening…',
  thinking: 'Thinking…',
  speaking: 'Speaking…',
  muted: 'Microphone muted',
  callEnded: 'Voice call ended',
  threads: 'Conversations',
  newChat: 'New chat',
  noThreads: 'No conversations yet',
  untitled: 'New conversation',
  delete: 'Delete conversation',
  approvalTitle: 'Waiting for your approval',
  approve: 'Approve',
  reject: 'Reject',
  submit: 'Submit',
  thought: 'Thought process',
  errorGeneric: 'Something went wrong. Please try again.',
  menu: 'Open conversations',
  close: 'Close',
  today: 'Today',
  earlier: 'Earlier',
  memory: 'Memory',
  memoryHint: 'What your assistant remembers',
  aboutYou: 'What I remember about you',
  aboutYouHint: 'Used in every conversation so you don’t have to repeat yourself.',
  savedFiles: 'Saved files',
  savedFilesHint: 'Notes and documents the assistant saved for you.',
  memoryEmpty: 'Nothing saved yet.',
  addNote: 'Add a note',
  notePlaceholder: 'e.g. I am allergic to penicillin',
  save: 'Save',
  cancel: 'Cancel',
  edit: 'Edit',
  deleteFile: 'Delete',
  retry: 'Try again',
  dismiss: 'Dismiss',
  errBusy: 'The assistant is busy right now. Please try again in a moment.',
  errServer: 'Could not reach the assistant. Check your internet and try again.',
  errThreadCreate: 'Could not start a new conversation. Please try again.',
  errThreadDelete: 'Could not delete that conversation. Please try again.',
  errVoiceStart: 'Could not start voice mode. Please try again.',
  errMic: 'Allow microphone access in Settings to use voice mode.',
  promptSymptoms: 'I have fever and headache',
  promptChild: 'My child has diarrhoea',
  promptBook: 'Help me book a checkup',
  promptScheme: 'Am I eligible for Ayushman Bharat?',
};

type Key = keyof typeof en;

const hi: Partial<Record<Key, string>> = {
  title: 'स्वस्थ साथी',
  subtitle: 'आपका स्वास्थ्य सहायक',
  open: 'स्वास्थ्य सहायक खोलें',
  emptyTitle: 'आज मैं आपकी क्या मदद करूँ?',
  emptyBody: 'लक्षण, दवाइयाँ, अपॉइंटमेंट या सरकारी योजनाओं के बारे में पूछें — लिखकर या बोलकर।',
  disclaimer: 'यह डॉक्टर नहीं है। आपातकाल में 108 पर कॉल करें।',
  placeholder: 'कुछ भी पूछें…',
  placeholderVoice: 'वॉइस कॉल में लिखें…',
  connecting: 'जुड़ रहा है…',
  listening: 'सुन रहा हूँ…',
  thinking: 'सोच रहा हूँ…',
  speaking: 'बोल रहा हूँ…',
  muted: 'माइक बंद है',
  callEnded: 'वॉइस कॉल समाप्त',
  threads: 'बातचीत',
  newChat: 'नई बातचीत',
  noThreads: 'अभी कोई बातचीत नहीं',
  untitled: 'नई बातचीत',
  approvalTitle: 'आपकी अनुमति का इंतज़ार',
  approve: 'अनुमति दें',
  reject: 'मना करें',
  submit: 'भेजें',
  errorGeneric: 'कुछ गलत हो गया। फिर से कोशिश करें।',
  retry: 'फिर से कोशिश करें',
  dismiss: 'बंद करें',
  errBusy: 'सहायक अभी व्यस्त है। थोड़ी देर बाद फिर कोशिश करें।',
  errServer: 'सहायक से जुड़ नहीं पाए। इंटरनेट जाँचें और फिर कोशिश करें।',
  errThreadCreate: 'नई बातचीत शुरू नहीं हो पाई। फिर कोशिश करें।',
  errThreadDelete: 'बातचीत हटाई नहीं जा सकी। फिर कोशिश करें।',
  errVoiceStart: 'वॉइस मोड शुरू नहीं हो पाया। फिर कोशिश करें।',
  errMic: 'वॉइस मोड के लिए सेटिंग्स में माइक की अनुमति दें।',
  today: 'आज',
  earlier: 'पहले',
  memory: 'याददाश्त',
  memoryHint: 'सहायक को क्या याद है',
  aboutYou: 'मुझे आपके बारे में क्या याद है',
  aboutYouHint: 'हर बातचीत में काम आता है, ताकि आपको बार-बार न बताना पड़े।',
  savedFiles: 'सहेजी गई फ़ाइलें',
  savedFilesHint: 'सहायक द्वारा आपके लिए सहेजे गए नोट्स।',
  memoryEmpty: 'अभी कुछ सहेजा नहीं गया।',
  addNote: 'नोट जोड़ें',
  notePlaceholder: 'जैसे: मुझे पेनिसिलिन से एलर्जी है',
  save: 'सहेजें',
  cancel: 'रद्द करें',
  edit: 'बदलें',
  deleteFile: 'हटाएँ',
  promptSymptoms: 'मुझे बुखार और सिरदर्द है',
  promptChild: 'मेरे बच्चे को दस्त हो रहे हैं',
  promptBook: 'जाँच बुक करने में मदद करें',
  promptScheme: 'क्या मैं आयुष्मान भारत के लिए पात्र हूँ?',
};

const bho: Partial<Record<Key, string>> = {
  ...hi,
  emptyTitle: 'आज हम रउआ के का मदद करीं?',
  placeholder: 'कुछुओ पूछीं…',
};

const table: Record<Lang, Partial<Record<Key, string>>> = { en, hi, bho };

export function useAssistantStrings() {
  const { lang } = useI18n();
  return (key: Key) => table[lang][key] ?? en[key];
}
